apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pubsub-keyvault # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    objects: |
      array:
        - |
          objectName: ak-rabbitmq-username
          objectType: secret
        - |
          objectName: ak-rabbitmq-password
          objectType: secret
        - |
          objectName: ak-mssql-sa-password
          objectType: secret
        - |
          objectName: ak-mssql-connectionstring
          objectType: secret
  secretObjects:
    - secretName: mssql-password
      type: Opaque
      data:
        - objectName: ak-mssql-sa-password # name of the mounted content to sync. this could be the object name or object alias
          key: mssql-password
    - secretName: mssql-connectionstring
      type: Opaque
      data:
        - objectName: ak-mssql-connectionstring # name of the mounted content to sync. this could be the object name or object alias
          key: mssql-connectionstring
    - secretName: rabbit-password
      type: Opaque
      data:
        - objectName: ak-rabbitmq-password # name of the mounted content to sync. this could be the object name or object alias
          key: rabbit-password
    - secretName: rabbit-username
      type: Opaque
      data:
        - objectName: ak-rabbitmq-username # name of the mounted content to sync. this could be the object name or object alias
          key: rabbit-username
