apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-mfolabs # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    objects: |
      array:
        - |
          objectName: rabbit-username             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: rabbit-password             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: mssql-password             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
  secretObjects:
    - secretName: mssql-password
      type: Opaque
      data:
        - objectName: mssql-password # name of the mounted content to sync. this could be the object name or object alias
          key: mssql-password
    - secretName: rabbit-password
      type: Opaque
      data:
        - objectName: rabbit-password # name of the mounted content to sync. this could be the object name or object alias
          key: rabbit-password
    - secretName: rabbit-username 
      type: Opaque
      data:
        - objectName: rabbit-username  # name of the mounted content to sync. this could be the object name or object alias
          key: rabbit-username