apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: console
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: console
    spec:
      containers:
        - env:
            - name: RabbitMQ__Hostname
              valueFrom:
                configMapKeyRef:
                  name: console
                  key: rabbitmq_hostname
            - name: RabbitMQ__Password
              value: admin
            - name: RabbitMQ__Username
              value: admin
          image: matthieuf/pubsub-console:1.0
          name: lab-console
          resources: {}
      restartPolicy: Always
status: {}
