apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mssql
  name: mssql
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: mssql
status:
  loadBalancer: {}
