apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mssql
  name: mssql
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: mssql
status:
  loadBalancer: {}
