apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-mfolabs # needs to be unique per namespace
spec:
  parameters:
    userAssignedIdentityID: 2977be69-0d95-418c-935b-69c3085616c4 # Setting this to use workload identity ClientID
    keyvaultName: kv-aptar-aks-form # Set to the name of your key vault
    tenantId: 1e2f522c-2662-4a18-938a-8b61a1ab92d1 # The tenant ID of the key vault